### PR TITLE
Prepare for SCRAPI

### PR DESCRIPTION
**Pull request by OR13**
This PR removes implementation details from the architecture, many of which are specific to SCRAPI.

### CODE REVIEW

**Comment by aj-stein-nist** [comment]
Re the SCRAPI I-D reference, it does not appear to be in the IETF Datatracker system at all and noticed when it wasn't listed or clicked on a link to search by I-D name and it returned no results, @OR13. That is why I asked about this on the mailing list.

https://datatracker.ietf.org/doc/search?name=draft-birkholz-scitt-scrapi&rfcs=on&activedrafts=on&olddrafts=on

https://mailarchive.ietf.org/arch/msg/scitt/AqHH6OUrc2Xzj81JI-fD4IUB91U/

Don't we need to take care of that issue for the short-hand references to work at all? Can it not be added to the tracker in advance of being adopted by the WG? (It seems some are added and "owned" by authors and not associated with the target WG in advance in some or not all cases. Sorry, I am new here.

**Comment by OR13** [comment]
@aj-stein-nist hmm, you are right... seems scrapi is not published well enough to be referenced... I will have to fix that, but apparently its not blocking the PR... which is weird.

**Comment by OR13** [comment]
PR against SCRAPI which can take some of these changes, but which I am intentionally leaving light.

https://github.com/ietf-scitt/draft-birkholz-scitt-scrapi/pull/7

**Comment by SteveLasker** [comment]
fixes #117

**Review by SteveLasker — CHANGES_REQUESTED** [review]
Will be LGTM with merger of #141

**Review by SteveLasker — APPROVED** [review]
LGTM

Per the editors call, there was a few open questions that @fournet was going to open new issues and prs for tracking. 
This PR completes the previous decision to segment the APIs into: https://github.com/ietf-scitt/draft-birkholz-scitt-scrapi/

**Pull request merged**
