### PR TITLE
Update architecture diagram

### PR DESCRIPTION
**Pull request by OR13**
This pull request:

- clarifies that multiple receipts are possible
- clarifies that issuers are not always artifact producers
- clarifies that transparency services are not artifact repositories
- clarifies that verifiers are not always relying parties
- clarifies that relying parties care about artifact transparency (not just verifying transparent statements)

Screenshot 2024-01-09 at 1 06 39 PM

### CODE REVIEW

**Review by aj-stein-nist — APPROVED** [review]

**Comment by aj-stein-nist** [comment]
> > What I don't like
> > 
> > * The one diagram we have will look overly complicated.
> 
> Sometimes things get more complicated before they get simpler.

Since I had volunteered in the past and the diagram will spur related cleanup, if we merge this one I am willing to break it out into a simpler one. The diagram update clarifies a lot of terminology and concept questions in the currently published diagram I didn't understand and per our discussion of #120 this clears a lot of that up.

So to recap, if we merge this one, I can PR a simpler one after this one is merged in.

**Review by SteveLasker — APPROVED** [review]
LGTM with new PR incremental updates to include a basic flow, and this more real-world capabilities of SCITT

**Comment by cabo** [comment]
I don't understand the word "Verify" here, but that may be RATS terminology I'm not familiar with.

**Comment by OR13** [comment]
Screenshot 2024-01-13 at 8 58 49 AM


I made some adjustments to the bottom based on feedback from @henkbirkholz and others.

- Removed Auditor (a special case of verifier)
- Clarified that SCITT verifiers perform several actions that distinguish them from OAuth or RATS verifiers.

As a general comment, we seem to have a mix of supply chain specific roles, like `Producer`, `Integrator` and `Distributor`, `Auditor?` and security oriented roles such as `Issuer`, `Verifier` and `Relying Parties`.

If its possible I think we should strive to not have this mix in our primary diagram.

We could conform to the supply chain specific terminology through the following changes.

- `Issuer` -> `Producer`
- `Verifier` -> `Auditor`
- `Relying Party` -> `Consumer`

Alternatively we could conform to the security terminology:

- `Producers` -> `Claims Providers`
- `Integrators` -> `Relying Party`
- `Distributors` -> `Relying Party`

**Comment by aj-stein-nist** [comment]
If we are going to possibly merge #161 in the future it seems good to merge this now or pull in changes before that is pulled in since that diagram appears to be based on significant changes from that.

**Review by fournet — CHANGES_REQUESTED** [review]
This is a change of terminology. Let's confirm we agree on it, and update the Terminology section accordingly. In pariticular, so far we agreed not to separate verifiers and relying parties. Let's also double-check those terms are Ok wrt RATS.

This illustrates one pattern of multiple registration, among others. Do we need this complexity here? Should we add other diagrams in the Federation section?

The diagram is not consistent on the flow of identity documents, which (I guess) should all flow to Verifiers and to Auditors.

**Comment by yogeshbdeshpande** [comment]
> illustrates one pattern of multiple registration, among others. Do we need this complexity here? Should we add other diagrams in the Federation section?

I am OK with `Issuer` to `Producer` however, I am not convinced that we should change `Relying Party` to anything else, as Relying party is more generic and also Consumer seems to mean that one consuming the Artefact which may not be necessarily true.

Also I do not agree with `Verifier` to `Auditor` change, would like to know more on the reason/rationale for this change.

An `Auditor` is a much more restrictive role however, a `Verifier` is a role performed by an entity (essentially `software`) which perfroms Cryptographic Verification of the Presence of a `Signed Statement` inside the log.

**Comment by SteveLasker** [comment]
Agreement to split this out into two actions:
- Update the first diagram to represent transparency service as plural (@yogeshbdeshpande)
- Add the dual implementation for identity documents and artifacts as an additional diagram
- Remove terminology changes, to track as a separate PR

@yogeshbdeshpande to take the pen on the next steps

**Pull request closed without merging**
