### PR TITLE
Separate roles from actions

### PR DESCRIPTION
**Pull request by SteveLasker**
From the editors call on 11/12/24
- With the addition of the relying party roles, make the top consistent
- Change the hanging text for sign/verify to actions
- Move Issuer as the entity that performs the actions
- Cleanup overly detailed row for COSE_SIGN1
- Narrow the diagram to avoid make warnings

image

### CODE REVIEW

**Review by yogeshbdeshpande — APPROVED** [review]
in general the concept LGTM! For future: Just a word of caution: We should make every effort to make the Architecture, look simple. Too many boxes, complicate the diagram.

**Comment by yogeshbdeshpande** [comment]
> in general the concept LGTM! For future: Just a word of caution: We should make every effort to make the Architecture, look simple. Too many boxes, complicate the diagram.

Also, any reason why you removed `cose_sign1` It was super helpful to understand that the Signed Statement was `cose_sign1`

**Review by OR13 — APPROVED** [review]

**Comment by OR13** [comment]
@yogeshbdeshpande the reason was to keep the diagram high level, and leave details to spec text

**Comment by SteveLasker** [comment]
> As expected, but I would like to amplify Yogesh's question.

We did discuss this on the call, and [@OR13 's comment](https://github.com/ietf-wg-scitt/draft-ietf-scitt-architecture/pull/312#issuecomment-2471246968) sums up our conversation:

@henkbirkholz, are you blocking, or are you ok if we merge the current simplified version?

**Comment by henkbirkholz** [comment]
I am okay with the new version. We might apply of different meaning to the term "simplified" ☺️

**Review by henkbirkholz — APPROVED** [review]

**Pull request merged**
