### PR TITLE
Remove Federation Section

### PR DESCRIPTION
**Pull request by OR13**
In case there is no consensus to remove Federation, I raised https://github.com/ietf-wg-scitt/draft-ietf-scitt-architecture/pull/195 to update it.

### CODE REVIEW

**Review by aj-stein-nist — APPROVED** [review]

**Comment by SteveLasker** [comment]
I'd suggest we've had a few different conversations about federation of everything in a transparency service, vs. selective promotion of a subset of information across Transparency Services.
The latter is the ability for a consumer of one or more Transparency Services to promote the content for a subset of their software.
Microsoft ships lots of software, However, a consumer may only want to promote the Office suite of products into their Transparency Service for internal validation.

I'd suggest the wording, as current, isn't well defined and I'd vote to cut this section until more well defined.

**Review by SteveLasker — APPROVED** [review]
LGTM

**Comment by ad-l** [comment]
If this is merged then we likely need additional text in the claim registration section to describe what a TS should do with existing receipts already attached to the claim.

**Comment by SteveLasker** [comment]
> If this is merged then we likely need additional text in the claim registration section to describe what a TS should do with existing receipts already attached to the claim.

Thanks, @ad-l 
Would you like to initiate that PR?

**Comment by pdxjohnny** [comment]
Where are we doing the consensus discussion on federation? I feel like I haven’t seen discussion on the lost recently

**Comment by SteveLasker** [comment]
Hi, John,
We've been discussing in these PRs and IETF calls. We're working towards a WG Last Call at 119, trimming elements that we don't feel are coming to closure. I know you've been doing some great work, and we can bring this back in with more clarity if you'd like to make a PR/Proposal.

**Pull request merged**
