### PR TITLE
Add sequence diagram

### PR DESCRIPTION
**Pull request by OR13**
This PR addresses https://github.com/ietf-wg-scitt/draft-ietf-scitt-architecture/issues/13

### CODE REVIEW

**Comment by OR13** [comment]
Feel free to make adjustments using: https://mermaid.live/edit#pako:eNqNU01v2zAM_SuEztkf8KE7ZAWWw3ZYe9ngiyLRMRF9uBLlwij630fZFZatyTadZOq9R_KZfFEmWlSdyvhUMBj8RPqUtO8DyJl0YjI06cBwyLlgeh9_TDpkCQh5ecA0k8EN9DUygsOBIQ5v7A4OwPqMkDBPMWQ6kiNeYIgJeESosoM2nAU3pWhL09ro8OHu7lq-Dh5HzJWOq8wUnVSHVUV7MNF7YkYLHMEjMoXT_6keILMOFo4L-AWM0-Qz6GMsXL9bsZuWi3GC_QbZj2jOW7ieK9q3c37DmfBZDHI4V3tbVimjtbUpY7Db5ZZ8s_wzii2Ua8nCiSmjRxGuigkN0vTWwV5-SPGYhHvdjSzmik7rG7IesHpaMn68MOH-Ism_nbiV7S8-XHTxpxc3zWjNdfA9FjA6AKeS-feOduv0XJokj5nJOZi1o5ZjHexEp3Gd7F_KBxj1jDJvYSBbdwkovBtrs8HVTgnHa7Kyey9VuFcC9dirTq5Wp3Ov-vAqOF04PizBqE5Kxp0qk9Xc9lR1g3ZZomiJY_qyLfO60zsl-_kjxoZ5_QnpGWCo

Github comments support mermaid:

~~~ text
``` mermaid
...
```
~~~

```mermaid
sequenceDiagram
    participant Issuer
    participant TransparencyService
    Note left of Issuer: I take responsibility for the artifacts I produce
    Issuer ->> TransparencyService: These are the policies I am committed to meeting
    Issuer ->> TransparencyService: I stand by my claims about my artifact
    loop Claims Check
        TransparencyService ->> TransparencyService: Review relevant claims and policies
    end
    TransparencyService ->> Issuer: Here is my endorsement and receipt
    Consumer->>TransparencyService: Is this artifact safe to use?
    loop Endorsement Check
        TransparencyService->>TransparencyService: Review relevant claims and endorsements
    end
     TransparencyService ->> Consumer: You can trust this artifact, the endorsement is still valid
     Note right of Consumer: I have confidence in the artifacts I consume
```

**Comment by SteveLasker** [comment]
@OR13, is this a draft PR?

**Comment by OR13** [comment]
Yes, of course... The svg build is currently bugging, I can't build the draft locally.

**Comment by OR13** [comment]
Animated nyancat for testing purposes only.

**Comment by OR13** [comment]
closing for now, well need to do this with `aasvg` until other options become available.

**Pull request closed without merging**
